#!/usr/bin/env -S uv run --quiet --with fonttools --with brotli --with pillow python
"""Generate everything under logo/ from the mark geometry and fonts/ in this repo.

    ./scripts/build-logo.py

The mark path below and the wordmark parameters are the only hand-authored
brand geometry. Every SVG and every raster under logo/ is derived from them, so
a change here is the one edit that moves the logo everywhere downstream.

Needs `rsvg-convert` on PATH (brew install librsvg) for the raster half.
"""

import base64
import io
import shutil
import subprocess
import sys
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "logo"
EXPORT = OUT / "export"

PINK, INK, WHITE, BG = "#E75A7C", "#000000", "#FFFFFF", "#0B0B0C"

# The tambourine mark: crescent arc plus five jingles. Hand-authored.
MARK = """  <path d="M 80,24 A 42,42 0 1,0 84,96 L 72,86 A 28,28 0 1,1 69,34 Z"/>
  <circle cx="50" cy="4" r="7"/>
  <circle cx="14" cy="22" r="7"/>
  <circle cx="2" cy="58" r="7"/>
  <circle cx="14" cy="94" r="7"/>
  <circle cx="46" cy="114" r="7"/>"""
MARK_BOUNDS = (-5.0, -3.0, 84.0, 121.0)

TEXT, WEIGHT = "notambourine", 800
SIZE, TRACKING = 60.0, -1.0
ORIGIN_X, BASELINE_Y = 62.0, 78.0
LOCKUP_PAD = 6.0

# Fraction of the square tile the mark's height occupies. The app tile pulls in
# so a rounded corner never crops a jingle; maskable clears Android's 80% safe
# circle. The favicon tile runs much closer to the edge because at 16px the
# crescent is about two pixels wide and any margin spent is a pixel lost.
FILL_BARE, FILL_TILE, FILL_MASKABLE, FILL_FAVICON = 0.92, 0.66, 0.52, 0.88
CORNER = 0.2237  # Apple's squircle radius as a fraction of the tile
CORNER_FAVICON = 0.18  # a squircle this small reads as a blur, so round it less


def outline_wordmark():
    """Trace `notambourine` from the repo's own Nunito, so paths cannot drift."""
    font = instantiateVariableFont(
        TTFont(ROOT / "fonts/nunito-latin-var.woff2"), {"wght": WEIGHT}, inplace=True
    )
    upem = font["head"].unitsPerEm
    glyphs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font["hmtx"]

    commands, bounds, x = [], None, ORIGIN_X
    for ch in TEXT:
        name = cmap[ord(ch)]
        # Font units go up, SVG user units go down, so the y scale is negated.
        t = Transform(SIZE / upem, 0, 0, -SIZE / upem, x, BASELINE_Y)

        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
        glyphs[name].draw(TransformPen(pen, t))
        if d := pen.getCommands():
            commands.append(d)

        bpen = BoundsPen(glyphs)
        glyphs[name].draw(TransformPen(bpen, t))
        if bpen.bounds:
            bounds = bpen.bounds if bounds is None else (
                min(bounds[0], bpen.bounds[0]), min(bounds[1], bpen.bounds[1]),
                max(bounds[2], bpen.bounds[2]), max(bounds[3], bpen.bounds[3]),
            )

        x += hmtx[name][0] * (SIZE / upem) + TRACKING

    return " ".join(commands), bounds


def square(fill_fraction):
    """Square viewBox centred on the mark, sized so it fills `fill_fraction`."""
    x0, y0, x1, y1 = MARK_BOUNDS
    side = (y1 - y0) / fill_fraction
    return (x0 + x1) / 2 - side / 2, (y0 + y1) / 2 - side / 2, side


def svg(body, view, fill, note):
    minx, miny, w, h = view
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{h:.0f}"'
        f' viewBox="{minx:.2f} {miny:.2f} {w:.2f} {h:.2f}" fill="{fill}">\n'
        f"  <!-- {note} Generated by scripts/build-logo.py - do not hand-edit. -->\n"
        f"{body}\n</svg>\n"
    )


def write(name, text):
    (OUT / name).write_text(text)
    print(f"  logo/{name}")


def build_svgs():
    word, word_bounds = outline_wordmark()

    minx = min(MARK_BOUNDS[0], word_bounds[0]) - LOCKUP_PAD
    miny = min(MARK_BOUNDS[1], word_bounds[1]) - LOCKUP_PAD
    lockup_view = (
        minx, miny,
        max(MARK_BOUNDS[2], word_bounds[2]) + LOCKUP_PAD - minx,
        max(MARK_BOUNDS[3], word_bounds[3]) + LOCKUP_PAD - miny,
    )
    lockup_body = f'{MARK}\n  <path d="{word}"/>'

    bare_x, bare_y, bare_side = square(FILL_BARE)
    bare_view = (bare_x, bare_y, bare_side, bare_side)

    for suffix, fill in (("", PINK), ("-white", WHITE), ("-ink", INK)):
        write(f"mark{suffix}.svg", svg(MARK, bare_view, fill, "Tambourine mark."))
        write(f"lockup{suffix}.svg", svg(
            lockup_body, lockup_view, fill,
            "Lockup, wordmark outlined - no font to load, so it renders the same"
            " in a browser, an email client, and any CLI rasterizer.",
        ))

    # Live-text twin: the only file an editor can retype. librsvg and resvg apply
    # letter-spacing differently than a browser and overrun this viewBox, so the
    # outlined lockup above is what every raster below is cut from.
    subset = base64.b64encode(
        (ROOT / "fonts/nunito-wordmark-800.woff2").read_bytes()
    ).decode()
    write("lockup-text.svg", svg(
        "  <defs>\n    <style>\n"
        "      @font-face{font-family:'NT Wordmark';font-weight:800;font-style:normal;"
        f"src:url(data:font/woff2;base64,{subset}) format('woff2')}}\n"
        "    </style>\n  </defs>\n"
        f"{MARK}\n"
        f'  <text x="{ORIGIN_X:.0f}" y="{BASELINE_Y:.0f}"'
        " font-family=\"'NT Wordmark', Nunito, system-ui, sans-serif\""
        f' font-size="{SIZE:.0f}" font-weight="{WEIGHT}"'
        f' letter-spacing="{TRACKING:.0f}">{TEXT}</text>',
        lockup_view, PINK,
        "Lockup with the wordmark as editable text, over a ten-glyph Nunito"
        " subset inlined as a data URI. Edit in Figma; rasterize lockup.svg.",
    ))

    tile_x, tile_y, tile = square(FILL_TILE)
    write("icon.svg", svg(
        f'  <rect x="{tile_x:.2f}" y="{tile_y:.2f}" width="{tile:.2f}"'
        f' height="{tile:.2f}" rx="{tile * CORNER:.2f}" fill="{BG}"/>\n{MARK}',
        (tile_x, tile_y, tile, tile), PINK,
        "App tile: mark on the brand's page canvas, opaque because iOS renders"
        " a transparent touch icon on black.",
    ))

    fav_x, fav_y, fav = square(FILL_FAVICON)
    write("favicon.svg", svg(
        f'  <rect x="{fav_x:.2f}" y="{fav_y:.2f}" width="{fav:.2f}"'
        f' height="{fav:.2f}" rx="{fav * CORNER_FAVICON:.2f}" fill="{BG}"/>\n{MARK}',
        (fav_x, fav_y, fav, fav), PINK,
        "Browser tab icon, cut tighter than icon.svg so the crescent survives"
        " 16px. Link this as rel=icon and let the SVG scale.",
    ))

    # iOS applies its own squircle mask, so a touch icon that rounds its own
    # corners gets rounded twice. Same padding as icon.svg, square edges.
    write("icon-square.svg", svg(
        f'  <rect x="{tile_x:.2f}" y="{tile_y:.2f}" width="{tile:.2f}"'
        f' height="{tile:.2f}" fill="{BG}"/>\n{MARK}',
        (tile_x, tile_y, tile, tile), PINK,
        "App tile, square edges, for a platform that masks the icon itself.",
    ))

    mask_x, mask_y, mask = square(FILL_MASKABLE)
    write("icon-maskable.svg", svg(
        f'  <rect x="{mask_x:.2f}" y="{mask_y:.2f}" width="{mask:.2f}"'
        f' height="{mask:.2f}" fill="{BG}"/>\n{MARK}',
        (mask_x, mask_y, mask, mask), PINK,
        "Android maskable: full-bleed tile, mark inside the 80% safe circle.",
    ))


def build_manifest():
    """Paths are relative to the manifest, so it works wherever logo/ is served."""
    icons = [
        ("export/icon-192.png", "192x192", "image/png", "any"),
        ("export/icon-512.png", "512x512", "image/png", "any"),
        ("export/icon-maskable-512.png", "512x512", "image/png", "maskable"),
        ("favicon.svg", "any", "image/svg+xml", "any"),
    ]
    rows = ",\n".join(
        f'    {{"src": "{src}", "sizes": "{sizes}", "type": "{mime}",'
        f' "purpose": "{purpose}"}}'
        for src, sizes, mime, purpose in icons
    )
    write("site.webmanifest", (
        "{\n"
        '  "name": "NoTambourine",\n'
        '  "short_name": "NoTambourine",\n'
        f'  "theme_color": "{BG}",\n'
        f'  "background_color": "{BG}",\n'
        '  "display": "standalone",\n'
        f'  "icons": [\n{rows}\n  ]\n'
        "}\n"
    ))


def png(source, size, name, height=None):
    args = ["rsvg-convert", "-w", str(size)]
    if height:
        args += ["-h", str(height)]
    subprocess.run(args + [str(OUT / source), "-o", str(EXPORT / name)], check=True)
    print(f"  logo/export/{name}")


def build_rasters():
    EXPORT.mkdir(parents=True, exist_ok=True)

    for size in (16, 32, 48):
        png("favicon.svg", size, f"favicon-{size}x{size}.png")
    png("icon-square.svg", 180, "apple-touch-icon.png")
    png("icon.svg", 192, "icon-192.png")
    png("icon.svg", 512, "icon-512.png")
    png("icon-maskable.svg", 512, "icon-maskable-512.png")

    for size in (256, 512, 1024):
        png("mark.svg", size, f"mark-{size}.png")
    png("mark-white.svg", 512, "mark-white-512.png")

    for suffix in ("", "-white", "-ink"):
        png(f"lockup{suffix}.svg", 1024, f"lockup{suffix}-1024.png")
    png("lockup.svg", 2048, "lockup-2048.png")

    # Pillow's ICO writer downsamples one image; feeding it the 48px render keeps
    # every frame cut from the vector rather than from a resized 16px bitmap.
    with Image.open(EXPORT / "favicon-48x48.png") as im:
        buf = io.BytesIO()
        im.save(buf, format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])
        (EXPORT / "favicon.ico").write_bytes(buf.getvalue())
    print("  logo/export/favicon.ico")


def main():
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert not found; brew install librsvg")
    OUT.mkdir(exist_ok=True)
    build_svgs()
    build_manifest()
    build_rasters()


if __name__ == "__main__":
    main()
