#!/usr/bin/env -S uv run --quiet --with fonttools --with brotli --with pillow python
"""Generate everything under logo/ from the mark geometry and fonts/ in this repo.

    ./scripts/build-logo.py

The mark path below and the wordmark parameters are the only hand-authored
brand geometry. Every SVG and every raster under logo/ is derived from them, so
a change here is the one edit that moves the logo everywhere downstream.

Needs `rsvg-convert` on PATH for the raster half; it ships in librsvg.
"""

import base64
import io
import shutil
import subprocess
import sys
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "logo"
EXPORT = OUT / "export"

PINK, INK, WHITE, BG = "#E75A7C", "#000000", "#FFFFFF", "#0B0B0C"

# The tambourine mark: crescent arc plus five jingles. Hand-authored.
MARK = """  <path d="M 80,24 A 42,42 0 1,0 84,96 L 72,86 A 28,28 0 1,1 69,34 Z"/>
  <circle cx="50" cy="4" r="7"/>
  <circle cx="14" cy="22" r="7"/>
  <circle cx="2" cy="58" r="7"/>
  <circle cx="14" cy="94" r="7"/>
  <circle cx="46" cy="114" r="7"/>"""
MARK_BOUNDS = (-5.0, -3.0, 84.0, 121.0)

TEXT, WEIGHT = "notambourine", 800
SIZE, TRACKING = 60.0, -1.0
ORIGIN_X, BASELINE_Y = 62.0, 78.0
LOCKUP_PAD = 6.0

# The monogram is the lockup truncated, not a second drawing: same face, same
# size, same origin, so the n nests into the crescent's mouth exactly as it
# does in the full lockup.
MONOGRAM = TEXT[:2]

# Fraction of the square tile the artwork's long side occupies. The app tile
# pulls in so a rounded corner never crops a jingle; maskable clears Android's
# 80% safe circle. The favicon tile runs much closer to the edge because at
# 16px the crescent is about two pixels wide and any margin spent is a pixel
# lost.
FILL_BARE, FILL_TILE, FILL_MASKABLE, FILL_FAVICON = 0.92, 0.74, 0.60, 0.94
CORNER = 0.2237  # Apple's squircle radius as a fraction of the tile
CORNER_FAVICON = 0.18  # a squircle this small reads as a blur, so round it less


def outline(text):
    """Trace `text` from the repo's own Nunito, so paths cannot drift."""
    font = instantiateVariableFont(
        TTFont(ROOT / "fonts/nunito-latin-var.woff2"), {"wght": WEIGHT}, inplace=True
    )
    upem = font["head"].unitsPerEm
    glyphs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font["hmtx"]

    commands, bounds, x = [], None, ORIGIN_X
    for ch in text:
        name = cmap[ord(ch)]
        # Font units go up, SVG user units go down, so the y scale is negated.
        t = Transform(SIZE / upem, 0, 0, -SIZE / upem, x, BASELINE_Y)

        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
        glyphs[name].draw(TransformPen(pen, t))
        if d := pen.getCommands():
            commands.append(d)

        bpen = BoundsPen(glyphs)
        glyphs[name].draw(TransformPen(bpen, t))
        if bpen.bounds:
            bounds = bpen.bounds if bounds is None else (
                min(bounds[0], bpen.bounds[0]), min(bounds[1], bpen.bounds[1]),
                max(bounds[2], bpen.bounds[2]), max(bounds[3], bpen.bounds[3]),
            )

        x += hmtx[name][0] * (SIZE / upem) + TRACKING

    return " ".join(commands), bounds


def union(a, b):
    return (min(a[0], b[0]), min(a[1], b[1]), max(a[2], b[2]), max(a[3], b[3]))


def square(bounds, fill_fraction):
    """Square viewBox centred on `bounds`, sized so its long side fills the tile."""
    x0, y0, x1, y1 = bounds
    side = max(x1 - x0, y1 - y0) / fill_fraction
    return (x0 + x1) / 2 - side / 2, (y0 + y1) / 2 - side / 2, side


def tile(body, bounds, fill_fraction, corner, note):
    x, y, side = square(bounds, fill_fraction)
    rx = f' rx="{side * corner:.2f}"' if corner else ""
    return svg(
        f'  <rect x="{x:.2f}" y="{y:.2f}" width="{side:.2f}" height="{side:.2f}"'
        f'{rx} fill="{BG}"/>\n{body}',
        (x, y, side, side), PINK, note,
    )


def svg(body, view, fill, note):
    minx, miny, w, h = view
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{h:.0f}"'
        f' viewBox="{minx:.2f} {miny:.2f} {w:.2f} {h:.2f}" fill="{fill}">\n'
        f"  <!-- {note} Generated by scripts/build-logo.py - do not hand-edit. -->\n"
        f"{body}\n</svg>\n"
    )


def write(name, text):
    (OUT / name).write_text(text)
    print(f"  logo/{name}")


# `#` closes a fragment and `<`/`>` end an attribute, so both have to go; the
# rest of the SVG is already URL-safe. Single quotes inside let the CSS value
# stay double-quoted, which is what keeps this readable in a diff.
def data_uri(text):
    flat = " ".join(text.split()).replace("> <", "><")
    escaped = (
        flat.replace("%", "%25")
        .replace("#", "%23")
        .replace('"', "'")
        .replace("<", "%3C")
        .replace(">", "%3E")
    )
    return f'url("data:image/svg+xml,{escaped}")'


def build_css(marks):
    """The artwork as CSS, for the surfaces that cannot inline markup.

    A Marpit deck is the case that forces this: the theme owns no element
    inside a slide, so a running footer can only reach the lockup through a
    background image, and a PDF printed with no origin to fetch from can only
    reach it as a data URI. Generated here rather than hand-pasted so the
    bytes cannot drift from logo/.
    """
    lines = [
        "/* =========================================================",
        "   NoTambourine: the artwork as CSS custom properties",
        "   ---------------------------------------------------------",
        "   Generated by scripts/build-logo.py - do not hand-edit.",
        "",
        "   Data URIs, so a deck theme, a print stylesheet, and an",
        "   offline .html snapshot all reach the artwork with no",
        "   origin to fetch from. The pink is baked in: a background",
        "   image cannot read `currentColor`, so a surface that needs",
        "   the mono artwork links logo/*-white.svg or logo/*-ink.svg",
        "   instead.",
        "   ========================================================= */",
        "",
        ":root {",
    ]
    for name, text in marks:
        lines.append(f"  --nt-{name}-url: {data_uri(text)};")
    lines.append("}")
    css = "\n".join(lines) + "\n"
    (ROOT / "logo-vars.css").write_text(css)
    print(f"  logo-vars.css ({len(css)} bytes)")


def build_svgs():
    word, word_bounds = outline(TEXT)
    mono, mono_bounds = outline(MONOGRAM)

    lockup_bounds = union(MARK_BOUNDS, word_bounds)
    lockup_view = (
        lockup_bounds[0] - LOCKUP_PAD, lockup_bounds[1] - LOCKUP_PAD,
        lockup_bounds[2] - lockup_bounds[0] + 2 * LOCKUP_PAD,
        lockup_bounds[3] - lockup_bounds[1] + 2 * LOCKUP_PAD,
    )
    lockup_body = f'{MARK}\n  <path d="{word}"/>'

    mono_body = f'{MARK}\n  <path d="{mono}"/>'
    mono_bounds = union(MARK_BOUNDS, mono_bounds)

    bare_x, bare_y, bare_side = square(MARK_BOUNDS, FILL_BARE)
    bare_view = (bare_x, bare_y, bare_side, bare_side)
    mx, my, mside = square(mono_bounds, FILL_BARE)
    mono_view = (mx, my, mside, mside)

    for suffix, fill in (("", PINK), ("-white", WHITE), ("-ink", INK)):
        mark = svg(MARK, bare_view, fill, "Tambourine mark.")
        lockup = svg(
            lockup_body, lockup_view, fill,
            "Lockup, wordmark outlined - no font to load, so it renders the same"
            " in a browser, an email client, and any CLI rasterizer.",
        )
        write(f"mark{suffix}.svg", mark)
        write(f"monogram{suffix}.svg", svg(
            mono_body, mono_view, fill,
            f"Mark with `{MONOGRAM}` nested in the crescent, transparent and"
            " square. The short form of the lockup: avatar, favicon, app tile.",
        ))
        write(f"lockup{suffix}.svg", lockup)
        # The pink pair is the only one a data URI carries; see build_css.
        if not suffix:
            build_css((("mark", mark), ("lockup", lockup)))

    # Live-text twin: the only file an editor can retype. librsvg and resvg apply
    # letter-spacing differently than a browser and overrun this viewBox, so the
    # outlined lockup above is what every raster below is cut from.
    subset = base64.b64encode(
        (ROOT / "fonts/nunito-wordmark-800.woff2").read_bytes()
    ).decode()
    write("lockup-text.svg", svg(
        "  <defs>\n    <style>\n"
        "      @font-face{font-family:'NT Wordmark';font-weight:800;font-style:normal;"
        f"src:url(data:font/woff2;base64,{subset}) format('woff2')}}\n"
        "    </style>\n  </defs>\n"
        f"{MARK}\n"
        f'  <text x="{ORIGIN_X:.0f}" y="{BASELINE_Y:.0f}"'
        " font-family=\"'NT Wordmark', Nunito, system-ui, sans-serif\""
        f' font-size="{SIZE:.0f}" font-weight="{WEIGHT}"'
        f' letter-spacing="{TRACKING:.0f}">{TEXT}</text>',
        lockup_view, PINK,
        "Lockup with the wordmark as editable text, over a ten-glyph Nunito"
        " subset inlined as a data URI. Edit in Figma; rasterize lockup.svg.",
    ))

    write("icon.svg", tile(
        mono_body, mono_bounds, FILL_TILE, CORNER,
        "App tile: monogram on the brand's page canvas, opaque because iOS"
        " renders a transparent touch icon on black.",
    ))

    write("favicon.svg", tile(
        mono_body, mono_bounds, FILL_FAVICON, CORNER_FAVICON,
        "Browser tab icon, cut tighter than icon.svg so the monogram survives"
        " 16px. Link this as rel=icon and let the SVG scale.",
    ))

    # iOS applies its own squircle mask, so a touch icon that rounds its own
    # corners gets rounded twice. Same padding as icon.svg, square edges.
    write("icon-square.svg", tile(
        mono_body, mono_bounds, FILL_TILE, 0,
        "App tile, square edges, for a platform that masks the icon itself.",
    ))

    write("icon-maskable.svg", tile(
        mono_body, mono_bounds, FILL_MASKABLE, 0,
        "Android maskable: full-bleed tile, monogram inside the 80% safe circle.",
    ))


def build_manifest():
    """Paths are relative to the manifest, so it works wherever logo/ is served."""
    icons = [
        ("export/icon-192.png", "192x192", "image/png", "any"),
        ("export/icon-512.png", "512x512", "image/png", "any"),
        ("export/icon-maskable-512.png", "512x512", "image/png", "maskable"),
        ("favicon.svg", "any", "image/svg+xml", "any"),
    ]
    rows = ",\n".join(
        f'    {{"src": "{src}", "sizes": "{sizes}", "type": "{mime}",'
        f' "purpose": "{purpose}"}}'
        for src, sizes, mime, purpose in icons
    )
    write("site.webmanifest", (
        "{\n"
        '  "name": "NoTambourine",\n'
        '  "short_name": "NoTambourine",\n'
        f'  "theme_color": "{BG}",\n'
        f'  "background_color": "{BG}",\n'
        '  "display": "standalone",\n'
        f'  "icons": [\n{rows}\n  ]\n'
        "}\n"
    ))


def png(source, size, name, height=None):
    args = ["rsvg-convert", "-w", str(size)]
    if height:
        args += ["-h", str(height)]
    subprocess.run(args + [str(OUT / source), "-o", str(EXPORT / name)], check=True)
    print(f"  logo/export/{name}")


def build_rasters():
    EXPORT.mkdir(parents=True, exist_ok=True)

    for size in (16, 32, 48):
        png("favicon.svg", size, f"favicon-{size}x{size}.png")
    png("icon-square.svg", 180, "apple-touch-icon.png")
    png("icon.svg", 192, "icon-192.png")
    png("icon.svg", 512, "icon-512.png")
    png("icon-maskable.svg", 512, "icon-maskable-512.png")

    for size in (256, 512, 1024):
        png("mark.svg", size, f"mark-{size}.png")
        png("monogram.svg", size, f"monogram-{size}.png")
    png("mark-white.svg", 512, "mark-white-512.png")
    png("monogram-white.svg", 512, "monogram-white-512.png")

    for suffix in ("", "-white", "-ink"):
        png(f"lockup{suffix}.svg", 1024, f"lockup{suffix}-1024.png")
    png("lockup.svg", 2048, "lockup-2048.png")

    # Pillow's ICO writer downsamples one image; feeding it the 48px render keeps
    # every frame cut from the vector rather than from a resized 16px bitmap.
    with Image.open(EXPORT / "favicon-48x48.png") as im:
        buf = io.BytesIO()
        im.save(buf, format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])
        (EXPORT / "favicon.ico").write_bytes(buf.getvalue())
    print("  logo/export/favicon.ico")


def main():
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert not found; install librsvg (macOS/Linux: brew install librsvg)")
    OUT.mkdir(exist_ok=True)
    build_svgs()
    build_manifest()
    build_rasters()


if __name__ == "__main__":
    main()
